import assert from 'node:assert/strict';
import {createWorker,cleanResult,DailyBudget} from './worker.mjs';
const origin='https://www.breezecompany.co.kr';
const image='data:image/jpeg;base64,/9j/AAAA';
const req=(body={task:'order',image,token:'proof'},overrides={})=>new Request('https://worker/analyze',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'192.0.2.1',...overrides},body:JSON.stringify(body)});
let upstream=0,budgetCalls=0;
const env={GROQ_API_KEY:'test-only',TURNSTILE_SECRET_KEY:'test-only',AI_RATE_LIMITER:{limit:async()=>({success:true})},AI_BUDGET:{idFromName:n=>n,get:()=>({fetch:async()=>{budgetCalls++;return new Response('',{status:200});}})}};
const http=async(url,options)=>{
 if(url.includes('siteverify'))return Response.json({success:true,hostname:'www.breezecompany.co.kr',action:'breeze-ai'});
 upstream++;const payload=JSON.parse(options.body);assert.equal(payload.model,'qwen/qwen3.6-27b');assert(!('tools' in payload));
 return Response.json({choices:[{message:{content:JSON.stringify({recipient:'테스트',date:'2026-09-20',purpose:'결혼',address:'테스트 장소'})}}]});
};
const worker=createWorker(http);
assert.equal((await worker.fetch(req(),{})).status,503);
assert.equal((await worker.fetch(req(undefined,{Origin:'https://evil.example'}),env)).status,403);
assert.equal((await worker.fetch(req({task:'order',image:'https://example.com/image.jpg',token:'proof'}),env)).status,400);
assert.equal((await worker.fetch(req({task:'arbitrary',image,token:'proof'}),env)).status,400);
assert.equal((await worker.fetch(req(undefined,{'Content-Length':'3000000'}),env)).status,413);
assert.equal((await worker.fetch(req(),{...env,AI_RATE_LIMITER:{limit:async()=>({success:false})}})).status,429);
assert.equal(upstream,0);
const badProof=createWorker(async()=>Response.json({success:false}));assert.equal((await badProof.fetch(req(),env)).status,403);
const wrongHost=createWorker(async()=>Response.json({success:true,hostname:'evil.example',action:'breeze-ai'}));assert.equal((await wrongHost.fetch(req(),env)).status,403);
const fullBudget={...env,AI_BUDGET:{idFromName:n=>n,get:()=>({fetch:async()=>new Response('',{status:429})})}};assert.equal((await worker.fetch(req(),fullBudget)).status,429);
assert.equal(upstream,0);
const success=await worker.fetch(req(),env);assert.equal(success.status,200);assert.equal((await success.json()).data.recipient,'테스트');assert.equal(upstream,1);assert.equal(budgetCalls,1);
assert.equal(cleanResult({date:'2026-02-31'},'order').date,'');assert.equal(cleanResult({recipient:{bad:true}},'order').recipient,'');
let record;const store={get:async()=>record,put:async(_,v)=>{record=v;}};const daily=new DailyBudget({storage:{transaction:fn=>fn(store)}},{AI_DAILY_LIMIT:'2'});
for(const code of [200,200,429])assert.equal((await daily.fetch(new Request('https://budget/consume',{method:'POST'}))).status,code);
const failed=createWorker(async(url)=>url.includes('siteverify')?Response.json({success:true,hostname:'www.breezecompany.co.kr',action:'breeze-ai'}):new Response('secret-provider-detail',{status:401}));
const error=await failed.fetch(req(),env);assert.equal(error.status,502);const errorBody=await error.json();assert.equal(errorBody.code,'AI_UPSTREAM_401');assert(!JSON.stringify(errorBody).includes('secret-provider-detail'));
console.log('PASS: origin, secret readiness, task/input limits, captcha verification, rate/daily budget, output schema, secret-safe errors');
